GET http://localhost:9091/api/poles


//PUT http://localhost:9091/api/poles/updateCapturedDates/all


//PUT http://dt14.idi.ntnu.no:9091/api/poles/69847a3299a15e54ca0f9699/date?newDate=2026-02-05

###

GET http://localhost:9091/api/poles/1771891200000